### ISSUE TITLE
its not working with my file

### ISSUE THREAD

**Issue by anshul1912** [amarghosh/mp4viewer#1]
here is where it fails
[anshul@daku_daddy src]$ python showboxes.py ~/test_videos/1.mp4
Traceback (most recent call last):
  File "showboxes.py", line 16, in getboxlist
    box = Box.getnextbox(buf, parent)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 115, in getnextbox
    box = Box(buf, parent, container)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 43, in **init**
    self.parse_children(buf)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 67, in parse_children
    box = Box.getnextbox(buf, self)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 115, in getnextbox
    box = Box(buf, parent, container)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 43, in **init**
    self.parse_children(buf)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 67, in parse_children
    box = Box.getnextbox(buf, self)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 115, in getnextbox
    box = Box(buf, parent, container)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 43, in **init**
    self.parse_children(buf)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 67, in parse_children
    box = Box.getnextbox(buf, self)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 115, in getnextbox
    box = Box(buf, parent, container)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 43, in **init**
    self.parse_children(buf)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 67, in parse_children
    box = Box.getnextbox(buf, self)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 115, in getnextbox
    box = Box(buf, parent, container)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 43, in **init**
    self.parse_children(buf)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 67, in parse_children
    box = Box.getnextbox(buf, self)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/isobmff/box.py", line 118, in getnextbox
    buf.skipbytes(box.size - box.consumed_bytes)
  File "/home/anshul/Downloads/mp4_view/mp4viewer-master/src/datasource.py", line 146, in skipbytes
    raise Exception("Negative bytes to skip %d" %(count))
Exception: Negative bytes to skip -8

  `---1.mp4
`---ftyp
              major brand: qt  
              minor version: 537199360
              brands: qt  ,,,

**Comment by amarghosh** [comment]
I know its very old, but can you by any chance share the file that you used?

**Comment by amarghosh** [comment]
Closing this as there is no response in five years.
